decrypt:
  settings.xml: "settings.xml.asc"
  pubring.gpg: "pubring.gpg.asc"
  secring.gpg: "secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy --settings /home/r/settings.xml
